"""DSL adapter — compiles NL constraints to verified code snippets via DSL_OR.

Flow:
  NL → nl_to_routing_optl() → OPTL source → compile_optl() → snippet

The OPTL source is the intermediate representation (OPTL's AST nodes).
The snippet is verified, deterministic code ready to inject into the solver.

The GA agent's only job in DSL mode: find old_text and wrap the snippet.
It must NOT rewrite the constraint logic.
"""

from __future__ import annotations

import sys
import os
from typing import Any

# DSL_OR is a sibling directory
_DSL_OR_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "DSL_OR")
if _DSL_OR_PATH not in sys.path:
    sys.path.insert(0, os.path.abspath(_DSL_OR_PATH))

from optl import compile_optl
from optl.routing import compile_routing_constraint, nl_to_routing_optl, RoutingParseError


class DSLCompileError(Exception):
    """Raised when NL parsing or snippet compilation fails."""


def compile_for_solver(
    constraint_nl: str,
    solver_type: str,
    max_retries: int = 2,
) -> dict[str, Any]:
    """Parse NL constraint and compile to a verified code snippet.

    Args:
        constraint_nl: Natural language constraint.
        solver_type: "insertion" or "hexaly".
        max_retries: LLM self-correction attempts.

    Returns:
        Dict with keys:
          - "optl_source" : OPTL source string (the IR)
          - "snippet"     : verified Python code snippet for injection
          - "solver"      : solver_type string
          - "constraint"  : original NL string

    Raises:
        DSLCompileError: If parsing or compilation fails.
    """
    # Map solver_type to OPTL backend name
    backend = "hexaly_routing" if solver_type == "hexaly" else "insertion"

    try:
        optl_source = nl_to_routing_optl(constraint_nl, solver=backend, max_retries=max_retries)
        snippet = compile_optl(optl_source, skip_verify=True)
    except RoutingParseError as e:
        raise DSLCompileError(f"NL → OPTL failed: {e}") from e
    except (ValueError, NotImplementedError) as e:
        raise DSLCompileError(f"Compilation failed: {e}") from e

    return {
        "optl_source": optl_source,
        "snippet": snippet,
        "solver": solver_type,
        "constraint": constraint_nl,
    }


def build_dsl_ga_prompt(result: dict[str, Any], source_summary: str) -> str:
    """Build the GA agent prompt for DSL mode.

    The GA only needs to find old_text and insert the pre-compiled snippet.

    Args:
        result: Output from compile_for_solver().
        source_summary: Full function source(s) from the pathfinder.

    Returns:
        Prompt string for the GA agent.
    """
    snippet = result["snippet"]
    solver = result["solver"]
    optl_source = result["optl_source"]
    constraint = result["constraint"]

    injection_note = (
        "Inject at the top of ``evaluate_bus_candidate``, after ``bus_id = bus[\"id\"]`` "
        "is set. The snippet must come BEFORE any other eligibility checks."
        if solver == "insertion" else
        "Inject OUTSIDE the per-vehicle ``for k in range(num_vehicles):`` loop, "
        "BEFORE ``model.close()``. The snippet already contains its own loop."
    )

    return f"""\
## Constraint
{constraint}

## OPTL source (verified intermediate representation)
```
{optl_source}
```

## Pre-compiled snippet (DO NOT modify the constraint logic)
This code was generated by a verified DSL compiler. Your ONLY job is to find
the correct old_text and insert this snippet. Do NOT rewrite or alter it.

```python
{snippet}
```

## Injection instructions
Solver: {solver}
{injection_note}

## Function source(s)
{source_summary}

Output the edit in the standard XML format:
<relative_path>filename.py</relative_path>
<old_text>exact lines to replace (at least 3 lines of context)</old_text>
<new_text>same lines with the snippet inserted</new_text>
<explanation>one sentence</explanation>
"""
